# Generated by Django 3.1.6 on 2021-02-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Start time')),
                ('end_date', models.DateTimeField(verbose_name='End time')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('order_start_date', models.DateTimeField(verbose_name='Start time')),
                ('order_end_date', models.DateTimeField(verbose_name='End time')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ticket')),
            ],
        ),
    ]
